app/__init__.py
from flask import Flask
from config import Config

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Register the blueprints
    from app.blueprints.home import bp as home
    from app.blueprints.main import bp as main
    app.register_blueprint(home)
    app.register_blueprint(main)
    
    return app

app/blueprints/home/__init__.py
from flask import Blueprint

bp = Blueprint('home', __name__, url_prefix='/')

from .import routes

app/blueprints/home/routes.py
from flask import request, render_template, redirect, url_for
from .import bp as app

@app.route('/')
@app.route('/home')
def home():
    return render_template('home.html')

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='/')

from .import routes

app/blueprints/main/routes.py
from flask import request, render_template, redirect\
    , url_for, current_app as app
from .import bp as app

@app.route('/about')
def about():
    return render_template('about.html')
@app.route('/contact')
def contact():
    return render_template('contact.html')

app/templates/about.html
{% extends 'base.html' %}

{% block title %}
  About
{% endblock %}

{% block content %}
  <div>
    <img class="about" src="/static/images/about.png">
  </div>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>
        {% block title %}
            
        {% endblock %}
    </title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>
  <body>
    <div>
        <header>
            <ul class="navbar navbar-expand-sm navbar-dark bg-dark">
                <li class="nav-item list-unstyled">
                    <a class="nav-link active" href="{{ url_for('home.home') }}">Home</a>
                </li>
                <li class="nav-item list-unstyled">
                    <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                </li>
                <li class="nav-item list-unstyled">
                    <a class="nav-link" href="{{ url_for('main.contact') }}">Contact</a>
                </li>
            </ul>
        </header>
        <main class="container">
            {% block content %}
            {% endblock %}
        </main>
    </div>
    <footer>
        <p>
            Shakti Shah
            <span class="float-left">
                &#9400;
            </span> 
        </p>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/contact.html
{% extends 'base.html' %}

{% block title %}
  Contact
{% endblock %}

{% block content %}
  <div>
    <img class="contact" src="/static/images/contact.png">
  </div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block title %}
  Home
{% endblock %}

{% block content %}
  <div>
    <img class="home" src="/static/images/home.png">
  </div>
{% endblock %}